version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8080:5000
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app

  db:
    image: mysql:latest
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: 'vnv_blog'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_SSL_MODE: 'DISABLED'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app

volumes:
  db-data:

networks:
  app:
    driver: bridge


